export interface Transaction {
  id: string;
  date: string; // ISO format
  ticker: string; // e.g., 'AAPL'
  transactionType: 'buy' | 'sell' | 'dividend';
  shares: number;
  sharePrice: number;
  fees: number;
  totalAmount: number;
  securityName?: string; // Company/security name (optional for backward compatibility)
}

/**
 * Represents the data required to create a new transaction, typically from a form.
 * The `id` is generated by the backend/service, and `totalAmount` is calculated from
 * shares and sharePrice.
 */
export type NewTransactionData = Omit<Transaction, 'id' | 'totalAmount'>;
