import { SecurityType } from './security.model';

export interface Transaction {
  id: string;
  date: string; // ISO format
  ticker: string; // e.g., 'AAPL'
  transactionType: 'buy' | 'sell' | 'dividend';
  shares: number;
  sharePrice: number;
  fees: number;
  totalAmount: number;
  tax?: number; // Tax withheld (for dividend transactions)
  securityName?: string; // Company/security name (optional for backward compatibility)
  securityType?: SecurityType;
}

/**
 * Represents the data required to create a new transaction, typically from a form.
 * The `id` is generated by the backend/service.
 * For buy/sell: `totalAmount` is calculated from shares and sharePrice.
 * For dividends: `totalAmount` is the Net Received amount (user input).
 */
export type NewTransactionData = Omit<Transaction, 'id'>;
